### ISSUE TITLE
Crash when launching a build with `minifyEnabled true`

### ISSUE THREAD

**Issue by TylerMcCraw** [ZacSweers/ticktock#32]
When launching an app with `minifyEnabled true`, I receive a crash with a ClassNotFoundException (see stacktrace below).

Seems like there ought to be a default proguard rule set up so that `AndroidTzdbRulesInitializer` isn't stripped.

Here is the complete stacktrace:
```
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.tzdb.startup.AndroidTzdbRulesInitializer
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: androidx.startup.StartupException: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.tzdb.startup.AndroidTzdbRulesInitializer
        at androidx.startup.a.a(AppInitializer.java:186)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.android.tzdb.startup.AndroidTzdbRulesInitializer
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at androidx.startup.a.a(AppInitializer.java:173)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "dev.zacsweers.ticktock.android.tzdb.startup.AndroidTzdbRulesInitializer" on path: DexPathList[[zip file "/data/app/~~aaa==/com.redacted.beta-TnFgwproPLfm87dk8g65mA==/base.apk"],nativeLibraryDirectories=[/data/app/~~aaa==/com.redacted.beta-aaa==/lib/arm64, /data/app/~~aaa==/com.redacted.beta-aaa==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at androidx.startup.a.a(AppInitializer.java:173) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by TylerMcCraw** [comment]
Adding the following to my proguard fixed it for now.
I'm not sure if this is what the final solution should be, but it would be great if the library handled this for us via included proguard rule(s).
```-keep class dev.zacsweers.ticktock.** { *; }```

**Comment by ZacSweers** [comment]
This is a bug in androidx.startup. Alpha 1 forgot to package proguard rules to keep initializer subtypes. Your workaround works for now. You can simplify it to just keep the initializer class

**Comment by TylerMcCraw** [comment]
Thanks. Anyone who is following along can find the relevant temporary fix for the androidx.startup issue here:
https://issuetracker.google.com/issues/160523404
Basically, you'll need to apply:
```
-keep class * extends androidx.startup.Initializer {
    # Keep the public no-argument constructor while allowing other methods to be optimized.
    <init>();
}
```
As seen in this recent (currently unreleased fix) by the Android team:
https://android-review.googlesource.com/c/platform/frameworks/support/+/1347583/
