### ISSUE TITLE
Ticktock crashes when updating AGP & Desugar

### ISSUE THREAD

**Issue by giangpham96** [ZacSweers/ticktock#58]
## What happened?
When I update AGP from 7.2.2 to 7.3.0 and Desugar from 1.1.6 to 1.2.0, Ticktock crashes with the following stacktrace
```
java.lang.Error: java.lang.ClassCastException: Cannot cast dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider to j$.time.zone.ZoneRulesProvider
    at j$.time.zone.ZoneRulesProvider$1.run(ZoneRulesProvider.java:165)
    at java.security.AccessController.doPrivileged(AccessController.java:43)
    at j$.time.zone.ZoneRulesProvider.<clinit>(ZoneRulesProvider.java:153)
    at j$.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:240)
    at j$.time.ZoneRegion.ofId(ZoneRegion.java:120)
    at j$.time.ZoneId.of(ZoneId.java:409)
    at j$.time.ZoneId.of(ZoneId.java:357)
```

## How to reproduce
In this [repo](https://github.com/giangpham96/ticktock-crash), you can find the working version in [main branch](https://github.com/giangpham96/ticktock-crash/tree/main) and the crash version in [crash branch](https://github.com/giangpham96/ticktock-crash/tree/crash)

If you can tell an workaround or create a hotfix, that would be superb

**Comment by giangpham96** [comment]
@ZacSweers maybe you know the answer?

**Comment by ZacSweers** [comment]
Please don't tag maintainers you don't know, it's quite rude

**Comment by giangpham96** [comment]
Apologize. 😔

**Comment by giangpham96** [comment]
This works again with AGP 7.4.0 and desugar 2.0.0
